export const QUERIES_KEYS = {
  GET_PRODUCTS: "GET_PRODUCTS",
  GET_CATEGORY: "GET_CATEGORY",
  REGISTER_USER: "REGISTER_USER",
  USER: "USER",
  SUBCATEGORY: "SUBCATEGORY",
  GET_TOPSALE_PRODUCT: "GET_TOPSALE_PRODUCT",
  GET_ORDER: "GET_ORDER",
};
